=== lurkingryuu/ABAC_Sak/static/schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "MuSimA ABAC Input Schema",
    "type": "object",
    "properties": {
        "subject_size": {
            "type": "integer",
            "minimum": 1
        },
        "object_size": {
            "type": "integer",
            "minimum": 1
        },
        "environment_size": {
            "type": "integer",
            "minimum": 1
        },
        "accepted_rules_count": {
            "type": "integer",
            "minimum": 0
        },
        "denied_rules_count": {
            "type": "integer",
            "minimum": 0
        },
        "subject_attributes_count": {
            "type": "integer",
            "minimum": 1
        },
        "object_attributes_count": {
            "type": "integer",
            "minimum": 1
        },
        "environment_attributes_count": {
            "type": "integer",
            "minimum": 1
        },
        "subject_attributes_values": {
            "type": "array",
            "items": {
                "type": "integer",
                "minimum": 1
            }
        },
        "object_attributes_values": {
            "type": "array",
            "items": {
                "type": "integer",
                "minimum": 1
            }
        },
        "environment_attributes_values": {
            "type": "array",
            "items": {
                "type": "integer",
                "minimum": 1
            }
        },
        "subject_distributions": {
            "$ref": "#/definitions/distribution_array"
        },
        "object_distributions": {
            "$ref": "#/definitions/distribution_array"
        },
        "environment_distributions": {
            "$ref": "#/definitions/distribution_array"
        }
    },
    "required": [
        "subject_size",
        "object_size",
        "environment_size",
        "accepted_rules_count",
        "denied_rules_count"
    ],
    "definitions": {
        "distribution_array": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "distribution": {
                        "type": "string",
                        "enum": [
                            "N",
                            "P",
                            "U"
                        ]
                    },
                    "mean": {
                        "type": "number"
                    },
                    "variance": {
                        "type": "number",
                        "minimum": 0
                    },
                    "lambda": {
                        "type": "number",
                        "minimum": 0
                    }
                },
                "required": [
                    "distribution"
                ]
            }
        }
    }
}

=== lurkingryuu/ABAC_Sak/dataset/input5.json
{
    "$schema": "/schema.json",
    "subject_size": 20,
    "object_size": 15,
    "environment_size": 5,
    "accepted_rules_count": 5,
    "denied_rules_count": 3,
    "subject_attributes_count": 6,
    "object_attributes_count": 5,
    "environment_attributes_count": 4,
    "subject_attributes_values": [
        6,
        5,
        4,
        3,
        2,
        3
    ],
    "object_attributes_values": [
        4,
        3,
        2,
        2,
        3
    ],
    "environment_attributes_values": [
        2,
        2,
        2,
        1
    ],
    "subject_distributions": [
        {
            "distribution": "N",
            "mean": 4,
            "variance": 2
        },
        {
            "distribution": "P",
            "lambda": 4
        },
        {
            "distribution": "U"
        },
        {
            "distribution": "N",
            "mean": 3,
            "variance": 2
        },
        {
            "distribution": "U"
        },
        {
            "distribution": "P",
            "lambda": 2
        }
    ],
    "object_distributions": [
        {
            "distribution": "P",
            "lambda": 3
        },
        {
            "distribution": "N"
        },
        {
            "distribution": "N"
        },
        {
            "distribution": "P",
            "lambda": 1
        },
        {
            "distribution": "U"
        }
    ],
    "environment_distributions": [
        {
            "distribution": "N",
            "mean": 1,
            "variance": 1
        },
        {
            "distribution": "P",
            "lambda": 2
        },
        {
            "distribution": "U"
        },
        {
            "distribution": "N"
        }
    ]
}
